version: 2.1

executors:
  node:
    working_directory: ~/microservices-demo
    docker:
      - image: circleci/node:10
        user: node

jobs:
  prerelease:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Setup NPM bin path
          command: |
            mkdir $HOME/.npm-global
            npm config set prefix '$HOME/.npm-global'
            echo 'export PATH=$HOME/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            echo $BASH_ENV
      - run:
          name: Install Architect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Architect Login
          command: architect login -u $ARCHITECT_USERNAME -p $ARCHITECT_PASSWORD
      - run:
          name: Push changed services
          command: for dir in $(git diff --dirstat=files,0 HEAD~1 src/ | sed -E 's/^[ 0-9.]+% //g'); do architect push -s $dir -t latest; done

  release:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Setup NPM bin path
          command: |
            mkdir $HOME/.npm-global
            npm config set prefix '$HOME/.npm-global'
            echo 'export PATH=$HOME/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Architect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Architect Login
          command: architect login -u $ARCHITECT_USERNAME -p $ARCHITECT_PASSWORD
      - run:
          name: Push changed services
          command: for dir in $(ls -d src/*); do architect push -s $dir -t $CIRCLE_TAG; done

workflows:
  version: 2
  prerelease-changed:
    jobs:
      - prerelease:
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - master
  release-all:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
