name: examples/boutique-cartservice
description: Shopping cart service powering the Boutique Shop example
keywords:
  - gcp
  - demo
  - ecommerce
  - shopping

services:
  cart-db:
    image: redis
    interfaces:
      main: 6379

  cartservice:
    build:
      context: ./
    interfaces:
      main: 8080
    environment:
      PORT: ${{ services.cartservice.interfaces.main.port }}
      LISTEN_ADDR: 0.0.0.0
      REDIS_ADDR: ${{ services.cart-db.interfaces.main.host }}:${{ services.cart-db.interfaces.main.port }}

interfaces:
  api:
    description: Exposes the cart service API to upstream callers
    url: ${{ services.cartservice.interfaces.main.url }}
