name: boutique-shop/frontend
description: Web application serving the boutique shop microservices demo

dependencies:
  boutique-shop/product-catalog: v1
  boutique-shop/currency: v1
  boutique-shop/shopping-cart: v1
  boutique-shop/recommendations: v1
  boutique-shop/shipping: v1
  boutique-shop/ads: v1
  boutique-shop/checkout: v1

services:
  frontend:
    build:
      context: ./
    interfaces:
      main: 8080
    environment:
      PORT: 8080
      PRODUCT_CATALOG_SERVICE_ADDR: ${{ dependencies['boutique-shop/product-catalog'].interfaces.api.host }}:${{ dependencies['boutique-shop/product-catalog'].interfaces.api.port }}
      CURRENCY_SERVICE_ADDR: ${{ dependencies['boutique-shop/currency'].interfaces.api.host }}:${{ dependencies['boutique-shop/currency'].interfaces.api.port }}
      CART_SERVICE_ADDR: ${{ dependencies['boutique-shop/shopping-cart'].interfaces.api.host }}:${{ dependencies['boutique-shop/shopping-cart'].interfaces.api.port }}
      RECOMMENDATION_SERVICE_ADDR: ${{ dependencies['boutique-shop/recommendations'].interfaces.api.host }}:${{ dependencies['boutique-shop/recommendations'].interfaces.api.port }}
      SHIPPING_SERVICE_ADDR: ${{ dependencies['boutique-shop/shipping'].interfaces.api.host }}:${{ dependencies['boutique-shop/shipping'].interfaces.api.port }}
      AD_SERVICE_ADDR: ${{ dependencies['boutique-shop/ads'].interfaces.api.host }}:${{ dependencies['boutique-shop/ads'].interfaces.api.port }}
      CHECKOUT_SERVICE_ADDR: ${{ dependencies['boutique-shop/checkout'].interfaces.api.host }}:${{ dependencies['boutique-shop/checkout'].interfaces.api.port }}

interfaces:
  frontend:
    description: Exposes the boutique shop webapp to upstream callers or the public web
    url: ${{ services.frontend.interfaces.main.url }}
