name: product-catalog
description: Product catalog service used as part of the boutique shop microservices demo

services:
  catalog:
    build:
      context: ./
    interfaces:
      main:
        port: 3550
        protocol: grpc
    environment:
      PORT: 3550

interfaces:
  api:
    description: Exposes the product catalog service to upstream requests
    url: ${{ services.catalog.interfaces.main.url }}
